stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/wine-quality.csv
    outs:
    - data/raw/wine-quality.csv
  
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/wine-quality.csv
    outs:
    - data/processed/train_wine-quality.csv
    - data/processed/test_wine-quality.csv

  train_and_evaluate:
    cmd: python src/train_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_wine-quality.csv
    - data/processed/test_wine-quality.csv
    - src/train_evaluate.py
    params:
    - estimstors.ElasticNet.params.alpha
    - estimstors.ElasticNet.params.l1_ratio
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_model/model.joblib